name: CI

permissions:
  contents: read

concurrency:
  group: >
    ci-${{ github.workflow }}-${{
      github.event_name == 'pull_request' &&
      github.event.pull_request.number ||
      github.ref
    }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JUST_VERSION: "1.51.0"
  RUMDL_VERSION: "0.1.94"
  TAPLO_VERSION: "0.10.0"
  TYPOS_VERSION: "1.46.1"
  UV_VERSION: "0.11.15"
  ZIZMOR_VERSION: "1.25.2"

jobs:
  ci:
    name: CI (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.11"
    steps:
      - name: Disable Git autocrlf on Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Install just
        uses: taiki-e/install-action@8f531eaecd1898bc3da7d104ad91bee98d1b97bd # v2.79.9
        with:
          tool: just@${{ env.JUST_VERSION }}

      - name: Install rumdl
        uses: taiki-e/install-action@8f531eaecd1898bc3da7d104ad91bee98d1b97bd # v2.79.9
        with:
          tool: rumdl@${{ env.RUMDL_VERSION }}

      - name: Install taplo
        uses: taiki-e/install-action@8f531eaecd1898bc3da7d104ad91bee98d1b97bd # v2.79.9
        with:
          tool: taplo-cli@${{ env.TAPLO_VERSION }}

      - name: Install typos-cli
        uses: taiki-e/install-action@8f531eaecd1898bc3da7d104ad91bee98d1b97bd # v2.79.9
        with:
          tool: typos-cli@${{ env.TYPOS_VERSION }}

      - name: Install zizmor
        uses: taiki-e/install-action@8f531eaecd1898bc3da7d104ad91bee98d1b97bd # v2.79.9
        with:
          tool: zizmor@${{ env.ZIZMOR_VERSION }}

      - name: Install shell script tools
        uses: taiki-e/install-action@8f531eaecd1898bc3da7d104ad91bee98d1b97bd # v2.79.9
        with:
          tool: shellcheck,shfmt

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force

      - name: Sync dependencies
        run: uv sync --locked --group dev

      - name: Run CI
        run: just ci
