name: CI

permissions:
  contents: read

concurrency:
  group: >
    ci-${{ github.workflow }}-${{
      github.event_name == 'pull_request' &&
      github.event.pull_request.number ||
      github.ref
    }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JUST_VERSION: "1.52.0"
  RUMDL_VERSION: "0.2.10"
  TAPLO_VERSION: "0.10.0"
  TYPOS_VERSION: "1.47.2"
  UV_VERSION: "0.11.19"
  ZIZMOR_VERSION: "1.25.2"
  CARGO_HTTP_MULTIPLEXING: "false"

jobs:
  ci:
    name: CI (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.13"
    steps:
      - name: Disable Git autocrlf on Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          toolchain: stable
          cache: false

      - name: Install just
        uses: taiki-e/cache-cargo-install-action@417450f3c33ee20393705369577571770643d4c7 # v3.0.7
        with:
          tool: just@${{ env.JUST_VERSION }}

      - name: Install rumdl
        uses: taiki-e/cache-cargo-install-action@417450f3c33ee20393705369577571770643d4c7 # v3.0.7
        with:
          tool: rumdl@${{ env.RUMDL_VERSION }}

      - name: Install taplo
        uses: taiki-e/cache-cargo-install-action@417450f3c33ee20393705369577571770643d4c7 # v3.0.7
        with:
          tool: taplo-cli@${{ env.TAPLO_VERSION }}

      - name: Install typos-cli
        uses: taiki-e/cache-cargo-install-action@417450f3c33ee20393705369577571770643d4c7 # v3.0.7
        with:
          tool: typos-cli@${{ env.TYPOS_VERSION }}

      - name: Install zizmor
        uses: taiki-e/cache-cargo-install-action@417450f3c33ee20393705369577571770643d4c7 # v3.0.7
        with:
          tool: zizmor@${{ env.ZIZMOR_VERSION }}

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force

      - name: Sync dependencies
        run: uv sync --locked --group dev

      - name: Run CI
        run: just ci
